name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Changing to src directory for building
      - name: Install dependencies and build
        run: npm ci && npm run build
        working-directory: src # Specifies that the run command should be executed in the src directory

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SWEENK_PROD }}"
          channelId: live
          projectId: sweenk-production-cloud
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
